### ISSUE TITLE
paging issues

### ISSUE THREAD

**Issue by justisGipson** [jschr/vscodethemes#207] opened 2021-07-14 15:27 UTC
paging is way off... when trying to go to the next page it will skip 2 or 3 pages. It started off fine, but the more I messed around in there, the more pages it would jump.

I am including a video to show

https://user-images.githubusercontent.com/42194039/125648866-987106c8-8e43-4a3f-8f61-2b8b377a433a.mov

**Comment by jschr** [comment] 2021-07-18 21:23
The `<<` and `>>` buttons are the "skip forward" or "skip backwards" buttons not next or prev page. I can see how that's confusing and will consider changing this.

Closing as not a bug but thanks for the feedback.

**Closed by jschr** 2021-07-18 21:23 UTC
